# Generated by Django 3.2.5 on 2022-01-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
