# Generated by Django 4.0.1 on 2022-01-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0010_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
            ],
        ),
    ]
