# Generated by Django 3.2.5 on 2022-02-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0012_gallary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caraousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
